### PR TITLE
Fix rolling with a target

### LINKED ISSUE #204: [Age of Sigmar: Soulbound System] Tartgetting
for some reason rolling attacks will not work with targeting a specif cenemy
<br/>**From**: clericsupplyco@gmail.com<br/>foundry: 12.331<br/>age-of-sigmar-soulbound: 7.0.1<br/>soulbound-bestiary: 4.0.0<br/>soulbound-core: 4.0.0<br/>soulbound-order: 4.0.0<br/>Active Modules: warhammer-lib

### PR DESCRIPTION
**Pull request by sharrap**
Fixes #204

- Separates the `token` vs `this.isToken` branches of `speakerData` to ensure no `||` fallback to a invalid branch.
- Gets rid of unnecessary and incorrect `.document` call on `token`.
- Removes double-computation of `data.targets` in `SoulboundTest` constructor.

Screenshot 2024-12-22 at 5 21 03 PM

### CODE REVIEW

File: scripts/actor/actor-soulbound.js [hunk 1]
```diff
@@ -306,11 +306,18 @@ export class SoulboundActor extends WarhammerActor {
...
-                scene : (token?.document || this.token).parent.id
+                token : token.id,
+                scene : token.parent.id
+            }
+        }
+        else if (this.isToken)
+        {
+            return {
+                token : this.token.id,
+                scene : this.token.parent.id
```
Comment (moo-man) [inline scripts/actor/actor-soulbound.js:320]: The only change needed for this to be fixed is the other one in `test.js`, I'm not sure what this is accomplishing?

Comment (sharrap) [reply scripts/actor/actor-soulbound.js]: You're right, I went backwards and I think it seemed necessary from that order, but upon doing some testing this can be dropped. Updated.
